
package view.admin;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import model.dbCon;

public class adminPesanan extends javax.swing.JPanel {

    private DefaultTableModel tableModel;

    /**
     * Creates new form adminTambahBarang
     */
    public adminPesanan() {
        initComponents();

        setupTable();
        loadDataPesanan();
    }

    private void setupTable() {
        String[] kolom = {"ID Pesanan", "User ID", "Total", "Status", "Waktu"};
        tableModel = new DefaultTableModel(null, kolom);
        jTable1.setModel(tableModel);
    }

    private void loadDataPesanan() {
        tableModel.setRowCount(0);

        try {
            Connection conn = dbCon.getConn();
            Statement stmt = conn.createStatement();
            String sql = "SELECT * FROM pesanan ORDER BY created_at DESC";

            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()) {
                String id = rs.getString("id");
                String userId = rs.getString("user_id");
                String total = rs.getString("total");
                String status = rs.getString("status");
                String waktu = rs.getString("created_at");

                Object[] data = {id, userId, total, status, waktu};
                tableModel.addRow(data);
            }
        } catch (Exception e) {
            System.err.println("Error load pesanan: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulPanel = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        judulPanel.setPreferredSize(new java.awt.Dimension(980, 100));
        judulPanel.setLayout(new java.awt.BorderLayout());

        judul.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("PESANAN");
        judulPanel.add(judul, java.awt.BorderLayout.CENTER);

        add(judulPanel, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel judulPanel;
    // End of variables declaration//GEN-END:variables
}
