
package view.admin;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import model.dbCon;

public class adminTambahBarang extends javax.swing.JPanel {

    private DefaultTableModel tableModel;

    /**
     * Creates new form adminTambahBarang
     */
    public adminTambahBarang() {
        initComponents();
        setupTable();
        loadDataBarang();
    }

    private void setupTable() {
        // isi kolom didalam tabel
        String[] kolom = {"ID", "Nama Produk", "Kategori", "Stok", "Harga"};
        tableModel = new DefaultTableModel(null, kolom);
        jTable1.setModel(tableModel);
    }

    private void loadDataBarang() {
        tableModel.setRowCount(0);
        try {
            Connection conn = dbCon.getConn();
            Statement stmt = conn.createStatement();
            String sql = "SELECT p.id, p.nama_produk, k.nama_kategori, p.stok, p.harga " +
                    "FROM produk p " +
                    "LEFT JOIN kategori k ON p.kategori_id = k.id";

            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                String id = rs.getString("id");
                String nama = rs.getString("nama_produk");
                String kat = rs.getString("nama_kategori");
                String stok = rs.getString("stok");
                String harga = rs.getString("harga");

                // masukiin data ke tabel
                Object[] data = {id, nama, kat, stok, harga};
                tableModel.addRow(data);
            }
        } catch (Exception e) {
            System.err.println("Gagal memuat data barang: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulPanel = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        judulPanel.setPreferredSize(new java.awt.Dimension(980, 100));
        judulPanel.setLayout(new java.awt.BorderLayout());

        judul.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("LIST BARANG");
        judulPanel.add(judul, java.awt.BorderLayout.CENTER);

        editBtn.setBackground(new java.awt.Color(204, 204, 204));
        editBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editBtn.setText("EDIT");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        judulPanel.add(editBtn, java.awt.BorderLayout.PAGE_END);

        add(judulPanel, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel judulPanel;
    // End of variables declaration//GEN-END:variables
}
