
package view.admin;

import javax.swing.JFrame;

public class adminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminDashboard.class.getName());
    /**
     * Creates new form adminPage
     */
    public adminDashboard() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        westPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        daftarBarangBtn = new javax.swing.JButton();
        pesananBtn = new javax.swing.JButton();
        profilBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        salam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        westPanel.setPreferredSize(new java.awt.Dimension(300, 720));
        westPanel.setLayout(new java.awt.BorderLayout());

        logoPanel.setPreferredSize(new java.awt.Dimension(300, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/admin/alfamart.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        westPanel.add(logoPanel, java.awt.BorderLayout.PAGE_START);

        daftarBarangBtn.setText("DAFTAR BARANG");
        daftarBarangBtn.setMaximumSize(new java.awt.Dimension(32767, 32767));
        daftarBarangBtn.setMinimumSize(new java.awt.Dimension(0, 0));
        daftarBarangBtn.setPreferredSize(new java.awt.Dimension(76, 50));
        daftarBarangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarBarangBtnActionPerformed(evt);
            }
        });

        pesananBtn.setText("PESANAN");
        pesananBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesananBtnActionPerformed(evt);
            }
        });

        profilBtn.setText("PROFIL");
        profilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(daftarBarangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pesananBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(profilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(daftarBarangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(pesananBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(profilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        westPanel.add(menuPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(westPanel, java.awt.BorderLayout.WEST);

        mainPanel.setLayout(new java.awt.BorderLayout());

        salam.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        salam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salam.setText("   SELAMAT DATANG, ADMIN");
        mainPanel.add(salam, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarBarangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarBarangBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(new adminTambahBarang(), java.awt.BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
        
    }//GEN-LAST:event_daftarBarangBtnActionPerformed

    private void profilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(new adminProfil(), java.awt.BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_profilBtnActionPerformed

    private void pesananBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesananBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(new adminPesanan(), java.awt.BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_pesananBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarBarangBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton pesananBtn;
    private javax.swing.JButton profilBtn;
    private javax.swing.JLabel salam;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables
}
