
package view.admin;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.UserSession;
import view.Login;

public class adminProfil extends javax.swing.JPanel {

    private JFrame parentFrame;

    /**
     * Creates new form adminProfil
     */

    public adminProfil(JFrame parent) {
        this.parentFrame = parent;
        initComponents();
        setupForm();
    }

    public adminProfil() {
        initComponents();
        setupForm();
    }

    private void loadProfileData() {
        // ambil data dari UserSession, dari login
        if(UserSession.getNama() != null) {
            namaAdmin.setText(UserSession.getNama());
            passwordAdmin.setText(UserSession.getPassword());
        }
    }

    private void setupForm() {
        // buat supaya nama dan password jadi read only
        namaAdmin.setEditable(false);
        passwordAdmin.setEditable(false);

        // ganti nama sama pass pake data dari db
        if (UserSession.getNama() != null) {
            namaAdmin.setText(UserSession.getNama());
            passwordAdmin.setText(UserSession.getPassword());
        } else {
            // kosong in case belum login
            namaAdmin.setText("");
            passwordAdmin.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePic = new javax.swing.JLabel();
        namaAdmin = new javax.swing.JTextField();
        passwordAdmin = new javax.swing.JTextField();
        logOut = new javax.swing.JButton();

        profilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/admin/profile.png"))); // NOI18N

        namaAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        namaAdmin.setText("NAMA ADMIN");
        namaAdmin.setPreferredSize(new java.awt.Dimension(93, 40));
        namaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaAdminActionPerformed(evt);
            }
        });

        passwordAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordAdmin.setText("PASSWORD ADMIN");
        passwordAdmin.setPreferredSize(new java.awt.Dimension(119, 40));
        passwordAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordAdminActionPerformed(evt);
            }
        });

        logOut.setBackground(new java.awt.Color(255, 0, 0));
        logOut.setText("LOG OUT");
        logOut.setPreferredSize(new java.awt.Dimension(100, 40));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.fill = java.awt.GridBagConstraints.NONE;
        
        gbc.gridy = 0;
        gbc.insets = new java.awt.Insets(0, 0, 36, 0);
        add(profilePic, gbc);
        
        gbc.gridy = 1;
        namaAdmin.setPreferredSize(new java.awt.Dimension(268, 40));
        namaAdmin.setMinimumSize(new java.awt.Dimension(268, 40));
        namaAdmin.setMaximumSize(new java.awt.Dimension(268, 40));
        add(namaAdmin, gbc);
        
        gbc.gridy = 2;
        passwordAdmin.setPreferredSize(new java.awt.Dimension(268, 40));
        passwordAdmin.setMinimumSize(new java.awt.Dimension(268, 40));
        passwordAdmin.setMaximumSize(new java.awt.Dimension(268, 40));
        add(passwordAdmin, gbc);
        
        gbc.gridy = 3;
        gbc.insets = new java.awt.Insets(0, 0, 0, 0);
        logOut.setPreferredSize(new java.awt.Dimension(120, 40));
        logOut.setMinimumSize(new java.awt.Dimension(120, 40));
        logOut.setMaximumSize(new java.awt.Dimension(120, 40));
        add(logOut, gbc);
    }// </editor-fold>//GEN-END:initComponents

    private void namaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaAdminActionPerformed

    private void passwordAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordAdminActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            UserSession.clear();
            //close panel
            if (parentFrame != null) {
                parentFrame.dispose();
            } else {
                javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
            }

            //pindah ke login
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logOut;
    private javax.swing.JTextField namaAdmin;
    private javax.swing.JTextField passwordAdmin;
    private javax.swing.JLabel profilePic;
    // End of variables declaration//GEN-END:variables
}
